### ISSUE TITLE
Ingesting fails on long csv lines

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#29]
When ingesting a csv, Beast can fail if line is longer than ~16kb. 

I'll investigate and will provide more details later.

**Comment by Legless** [comment]
Sorry, it's 128kb actually.

```
Traceback (most recent call last):
  File "/usr/src/thebeast/./beast.py", line 13, in <module>
    mapping.dumper.write_entities(
  File "/usr/src/thebeast/thebeast/dump/statements.py", line 94, in write_entities
    for entity in entities:
  File "/usr/local/lib/python3.11/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/src/thebeast/thebeast/digest/abstract.py", line 192, in extract
    for entity in self.run_the_cog(
  File "/usr/src/thebeast/thebeast/digest/single.py", line 20, in run_the_cog
    for record in records:
  File "/usr/local/lib/python3.11/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/src/thebeast/thebeast/ingest/abstract.py", line 81, in iterator
    for i, record in enumerate(self.reader(fp)):
  File "/usr/src/thebeast/thebeast/ingest/mixins.py", line 53, in reader
    for line in csv.DictReader(iterator, **self.dialect_params):
  File "/usr/local/lib/python3.11/csv.py", line 111, in __next__
    row = next(self.reader)
          ^^^^^^^^^^^^^^^^^
_csv.Error: field larger than field limit (131072)
```

It's a python csv lib [error](https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072), I see three options:
- ignore such rows completely (if it's possible?) - don't like it;
- set larger limit (maybe in `ingest` config section) - looks ok for me;
- set limit and a flag to skip such rows (in case of completely broken csv with huge rows of garbage) - looks even more ok for me;

**Comment by dchaplinsky** [comment]
https://stackoverflow.com/a/15063941

**Comment by Legless** [comment]
> https://stackoverflow.com/a/15063941

Yep, I've linked this in my comment. 😎

I mean, is it ok to let user set this value from ingestor config?

**Comment by dchaplinsky** [comment]
Yes it is.
